services:
   pulpmedia_ng_http.response.factory:
       class: Pulpmedia\NgHttpBundle\Services\ResponseFactory
       arguments: ["@jms_serializer"]
   pulpmedia_ng_http.form.errors_serializer:
       class: Pulpmedia\NgHttpBundle\Services\FormErrorsSerializer
   pulpmedia_ng_http.form.type.entity_hidden:
       class: Pulpmedia\NgHttpBundle\Form\Type\EntityHiddenType
       arguments: ["@doctrine.orm.entity_manager"]
       tags:
         - { name: form.type, alias: entity_hidden }
   pulpmedia_ng_http.authentication_handler:
       class:  Pulpmedia\NgHttpBundle\Handler\AuthenticationHandler
       arguments:  ["@pulpmedia_ng_http.response.factory"]
       tags:
         - { name: 'monolog.logger', channel: 'security' }
